#!/bin/bash
echo "Starting import"
sleep 15

echo "Update the JWKS of client one and two"
# client_one's own sig key follows CRYPTO_PROFILE too (ML-DSA-65 in pqc
# mode, see thesis/scripts/pqc-signer/; RS256 alg in hybrid mode, see
# Decision 13) -- client_two is never driven by opin_flow.py, so it stays
# on its original classical JWKS regardless. client_one_hybrid_pub.jwks
# (same RSA key/kid as client_one_pub.jwks, just "alg": "RS256" instead of
# "PS256") exists specifically so a real, standards-compliant JWKS
# consumer doing ordinary kid+alg discovery finds a matching, correctly-
# labeled key -- registering the plain client_one_pub.jwks here (still
# "alg": "PS256") would make such a consumer reject client_one's
# RS256-signed assertions outright, confirmed empirically with
# jose.createLocalJWKSet before this fix existed. Not generated by
# certs/main.go like the other profile-specific JWKS files (that tool has
# no notion of "same key, different published alg") -- committed directly.
CLIENT_ONE_JWKS="$2/certs/client_one_pub.jwks"
if [ "${CRYPTO_PROFILE:-classic}" = "pqc" ]; then
  CLIENT_ONE_JWKS="$2/certs/client_one_pqc_pub.jwks"
elif [ "${CRYPTO_PROFILE:-classic}" = "hybrid" ]; then
  CLIENT_ONE_JWKS="$2/certs/client_one_hybrid_pub.jwks"
fi
jq --argjson jwks1 "$(jq . < $CLIENT_ONE_JWKS)" \
   --argjson jwks2 "$(jq . < $2/certs/client_two_pub.jwks)" \
   '.[0].payload.jwks = $jwks1 | .[1].payload.jwks = $jwks2' \
   $2/init_clients.json > $2/init_clients.json.tmp && mv $2/init_clients.json.tmp $2/init_clients.json

# oidc-provider validates a client's full registered metadata on every
# authentication (confirmed empirically -- e.g. redirect_uris and this
# field both get checked even on a client_credentials grant, which touches
# neither). id_token_signed_response_alg has to match whichever algorithm
# the AS is actually signing with (cryptoProfile.signingAlgs[0] in
# mock_as/utils/opin/configuration.js), or every authentication for
# client_one/client_two fails with "id_token_signed_response_alg must be
# '<profile's algorithm>'" -- this file is a static seed, so it can't
# derive that itself; CRYPTO_PROFILE must be passed to this container the
# same way it already is to auth/mockapi.
ID_TOKEN_ALG="PS256"
if [ "${CRYPTO_PROFILE:-classic}" = "pqc" ]; then
  ID_TOKEN_ALG="ML-DSA-65"
fi
echo "Setting id_token_signed_response_alg=$ID_TOKEN_ALG for client_one/client_two (CRYPTO_PROFILE=${CRYPTO_PROFILE:-classic})"
jq --arg alg "$ID_TOKEN_ALG" \
   '.[0].payload.id_token_signed_response_alg = $alg | .[1].payload.id_token_signed_response_alg = $alg' \
   $2/init_clients.json > $2/init_clients.json.tmp && mv $2/init_clients.json.tmp $2/init_clients.json

# mongosh and the mongoimport/database-tools binaries use different flag
# names for the exact same thing (--tls/--tlsCAFile vs. the legacy
# --ssl/--sslCAFile) even though they ship in the same mongo:latest image.
MONGOSH_TLS_OPTS="--tls --tlsCAFile /certs/ca.crt"
MONGOIMPORT_TLS_OPTS="--ssl --sslCAFile /certs/ca.crt"

mongosh --host "$1" $MONGOSH_TLS_OPTS --eval "db = db.getSiblingDB('openid-server'); db.client.drop()"
mongoimport --host $1 $MONGOIMPORT_TLS_OPTS --db openid-server --collection client --type json --file $2/init_clients.json --jsonArray
mongoimport --host $1 $MONGOIMPORT_TLS_OPTS --db accounts --collection accounts --type json --file $2/init_accounts.json --jsonArray
mongoimport --host $1 $MONGOIMPORT_TLS_OPTS --db accounts --collection credentials --type json --file $2/init_credentials.json --jsonArray

echo "Stopping Import"
